### ISSUE TITLE
panics when decoding response body

### ISSUE THREAD

**Issue by andrewzah** [tobymurray/mr_splashy_pants#6]
I set up a bot to watch subreddit submissions, and I get this error after a bit of time:

stacktrace:

```
thread 'main' panicked at 'Error streaming: error decoding response body: invalid type: null, expected i64 at line 1 column 436', /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/macros.rs:16:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:217
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:526
  11: rust_begin_unwind
             at src/libstd/panicking.rs:437
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:391
  13: <async_stream::async_stream::AsyncStream<T,U> as futures_core::stream::Stream>::poll_next
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  15: std::thread::local::LocalKey<T>::with
  16: tokio::macros::scoped_tls::ScopedKey<T>::set
  17: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
  18: tokio::runtime::context::enter
  19: tokio::runtime::handle::Handle::enter
  20: sub_watcher::main
  21: std::rt::lang_start::{{closure}}
  22: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  23: std::panicking::try::do_call
             at src/libstd/panicking.rs:348
  24: std::panicking::try
             at src/libstd/panicking.rs:325
  25: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  26: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  27: main
  28: __libc_start_main
  29: _start
```

the rust code:

```rust
#[tokio::main]
async fn main() -> Result<(), Box<dyn Error>> {
    let user_agent = env::var("BOT_USER_AGENT")
        .expect("BOT_USER_AGENT is not set");
    let access_token = env::var("BOT_ACCESS_TOKEN")
        .expect("BOT_ACCESS_TOKEN is not set");
    let refresh_token = env::var("BOT_REFRESH_TOKEN")
        .expect("BOT_REFRESH_TOKEN is not set");
    let client_id = env::var("BOT_CLIENT_ID")
        .expect("BOT_CLIENT_ID is not set");
    let client_secret = env::var("BOT_CLIENT_SECRET")
        .expect("BOT_CLIENT_SECRET is not set");

    let mut pants = Pants::new(&user_agent, &access_token,
        refresh_token, &client_id, &client_secret);

    let subreddit = env::var("BOT_SUBREDDIT")?;
    let stream = pants.stream_subreddit_new(&subreddit);
    pin_mut!(stream);

    println!("[init] ok, listening now");
    while let Some(value) = stream.next().await {
       // do stuff
    }

    Ok(())
```

**Comment by tobymurray** [comment]
I think this is coming from the intrinsically difficult task of trying to provide a typed response from an API that is not consistent. The most robust integration would be to have every property be optional all the time, but from a usability perspective that kind of sucks. The most usable option would be to have a stable specification of the response from Reddit that differentiates between required and optional fields, but that's not likely forthcoming.

Noting that a panic is not good (should be fixed), from a usability perspective how much does it suck if every field is optional?

Out of curiosity, did it die almost immediately?

**Comment by tobymurray** [comment]
What version are you using?

**Comment by andrewzah** [comment]
@tobymurray so far I haven't been tracking timestamps. ~~Maybe it's happening with the refresh token after an hour?~~

I'm using version `0.1`.

For the model specification, if a response has a potentially null field should be an Option<T>, since the user can write macros or helpers to reduce code. You could keep this as an internal API for working with reddit, then have another model in the public API that has a method like `fn Id() -> Option<T> {}`, but personally I don't find it that bothersome to deal with `Option`s.

**Comment by andrewzah** [comment]
I got some timestamps:

| event | timestamp |
| --- | --- |
| initialization | 2020-09-16T16:30:30.073211056Z |
| error | 2020-09-16T16:56:17.618482886Z |
| | |
| initialization | 2020-09-16T17:56:27.783632802Z |
| error |  2020-09-16T18:14:39.813132847Z  |

**Comment by tobymurray** [comment]
Awesome - thanks for the bug report. I'm able to reproduce it readily, so I'll sort it out. As it stands, I expect the streaming functionality to be effectively unusable - it'll crash almost constantly on busy subreddits.

**Comment by tobymurray** [comment]
I've just pushed 0.1.19 which I hope side steps the issue in the short term (wraps all properties in `Option`). There are a handful of things that could be dramatically nicer, and a handful of places where it can still easily break (things I've defined as ints showing up as floats, for example). Testing it locally it lasts longer without blowing up, I'll let it sit and see what happens.

If you get a chance to try it again, let me know if it works for you.

**Comment by andrewzah** [comment]
@tobymurray it looks like that was fixed, but now it panics on trying to access `access_token`:

```
thread 'main' panicked at 'Panic! reqwest::Error {
    kind: Decode,
    source: Error("missing field `access_token`", line: 1, column: 40),
}', /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/macros.rs:16:9
stack backtrace:
   0:     0x560090718f85 - backtrace::backtrace::libunwind::trace::h14d338b30b3ea0a7
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x560090718f85 - backtrace::backtrace::trace_unsynchronized::h73ea91d74a3fd67f
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x560090718f85 - std::sys_common::backtrace::_print_fmt::hd42948c952866e12
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x560090718f85 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha8f928866ff7571e
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x56009073ddac - core::fmt::write::he0c1e5f7426d2718
                               at src/libcore/fmt/mod.rs:1076
   5:     0x5600907139b2 - std::io::Write::write_fmt::hf3afc6cfd57d0033
                               at src/libstd/io/mod.rs:1537
   6:     0x56009071b620 - std::sys_common::backtrace::_print::hfc0110703f3696fd
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x56009071b620 - std::sys_common::backtrace::print::h3f77c6990ddfaa22
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x56009071b620 - std::panicking::default_hook::{{closure}}::heae49580a8d62d75
                               at src/libstd/panicking.rs:198
   9:     0x56009071b36c - std::panicking::default_hook::hecc34e3f729e213c
                               at src/libstd/panicking.rs:217
  10:     0x56009071bc63 - std::panicking::rust_panic_with_hook::he82f5d0644692441
                               at src/libstd/panicking.rs:526
  11:     0x56009071b85b - rust_begin_unwind
                               at src/libstd/panicking.rs:437
  12:     0x56009071b7cb - std::panicking::begin_panic_fmt::h905a6d44880d49ef
                               at src/libstd/panicking.rs:391
  13:     0x5600903d1752 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hd57cee95db9d0eaf
  14:     0x56009040b2c0 - <async_stream::async_stream::AsyncStream<T,U> as futures_core::stream::Stream>::poll_next::h08a6deffd753621f
  15:     0x5600903cd4e6 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h810ee83916758643
  16:     0x5600903d26db - std::thread::local::LocalKey<T>::with::h3580e85ec25d6096
  17:     0x5600903e1c0a - tokio::macros::scoped_tls::ScopedKey<T>::set::hbdf37f72af537fad
  18:     0x5600903f344a - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::hd127be604a6b9a94
  19:     0x56009041154d - tokio::runtime::context::enter::haf2e13e89fefc440
  20:     0x5600903f3571 - tokio::runtime::handle::Handle::enter::h3e8d78e21dd1ae45
  21:     0x560090413ee6 - sub_watcher::main::hbec737c25c32569c
  22:     0x5600903d25c3 - std::rt::lang_start::{{closure}}::ha7e09ce54e772948
  23:     0x56009071c103 - std::rt::lang_start_internal::{{closure}}::h5d3ea623498f5f43
                               at src/libstd/rt.rs:52
  24:     0x56009071c103 - std::panicking::try::do_call::hac65e71be769a440
                               at src/libstd/panicking.rs:348
  25:     0x56009071c103 - std::panicking::try::hd4706e264bcf6712
                               at src/libstd/panicking.rs:325
  26:     0x56009071c103 - std::panic::catch_unwind::h948a0fb4a8b3ee82
                               at src/libstd/panic.rs:394
  27:     0x56009071c103 - std::rt::lang_start_internal::h72cc068ed2d0ac53
                               at src/libstd/rt.rs:51
  28:     0x560090413ff2 - main
  29:     0x7f3c2556909b - __libc_start_main
  30:     0x56009037518a - _start
  31:                0x0 - <unknown>

```

**Comment by tobymurray** [comment]
I'll move this to a new bug just for the sake of organization. Created #8
