### ISSUE TITLE
panic on Connection Reset - reqwest::Error

### ISSUE THREAD

**Issue by andrewzah** [tobymurray/mr_splashy_pants#7]
```
thread 'main' panicked at 'Panic!', /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/macros.rs:13:23
stack backtrace:
Everything failed! reqwest::Error {
    kind: Request,
    url: "https://oauth.reddit.com/r/frugalmalefashion/new",
    source: hyper::Error(
        Io,
        Os {
            code: 104,
            kind: ConnectionReset,
            message: "Connection reset by peer",
        },
    ),
}
   0:     0x55d20886bf85 - backtrace::backtrace::libunwind::trace::h14d338b30b3ea0a7
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x55d20886bf85 - backtrace::backtrace::trace_unsynchronized::h73ea91d74a3fd67f
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x55d20886bf85 - std::sys_common::backtrace::_print_fmt::hd42948c952866e12
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x55d20886bf85 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha8f928866ff7571e
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x55d208890dac - core::fmt::write::he0c1e5f7426d2718
                               at src/libcore/fmt/mod.rs:1076
   5:     0x55d2088669b2 - std::io::Write::write_fmt::hf3afc6cfd57d0033
                               at src/libstd/io/mod.rs:1537
   6:     0x55d20886e620 - std::sys_common::backtrace::_print::hfc0110703f3696fd
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x55d20886e620 - std::sys_common::backtrace::print::h3f77c6990ddfaa22
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55d20886e620 - std::panicking::default_hook::{{closure}}::heae49580a8d62d75
                               at src/libstd/panicking.rs:198
   9:     0x55d20886e36c - std::panicking::default_hook::hecc34e3f729e213c
                               at src/libstd/panicking.rs:217
  10:     0x55d20886ec63 - std::panicking::rust_panic_with_hook::he82f5d0644692441
                               at src/libstd/panicking.rs:526
  11:     0x55d20854c80e - std::panicking::begin_panic::h504bebd16671910e
  12:     0x55d208524413 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hd57cee95db9d0eaf
  13:     0x55d20855e2c0 - <async_stream::async_stream::AsyncStream<T,U> as futures_core::stream::Stream>::poll_next::h08a6deffd753621f
  14:     0x55d2085204e6 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h810ee83916758643
  15:     0x55d2085256db - std::thread::local::LocalKey<T>::with::h3580e85ec25d6096
  16:     0x55d208534c0a - tokio::macros::scoped_tls::ScopedKey<T>::set::hbdf37f72af537fad
  17:     0x55d20854644a - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::hd127be604a6b9a94
  18:     0x55d20856454d - tokio::runtime::context::enter::haf2e13e89fefc440
  19:     0x55d208546571 - tokio::runtime::handle::Handle::enter::h3e8d78e21dd1ae45
  20:     0x55d208566ee6 - sub_watcher::main::hbec737c25c32569c
  21:     0x55d2085255c3 - std::rt::lang_start::{{closure}}::ha7e09ce54e772948
  22:     0x55d20886f103 - std::rt::lang_start_internal::{{closure}}::h5d3ea623498f5f43
                               at src/libstd/rt.rs:52
  23:     0x55d20886f103 - std::panicking::try::do_call::hac65e71be769a440
                               at src/libstd/panicking.rs:348
  24:     0x55d20886f103 - std::panicking::try::hd4706e264bcf6712
                               at src/libstd/panicking.rs:325
  25:     0x55d20886f103 - std::panic::catch_unwind::h948a0fb4a8b3ee82
                               at src/libstd/panic.rs:394
  26:     0x55d20886f103 - std::rt::lang_start_internal::h72cc068ed2d0ac53
                               at src/libstd/rt.rs:51
  27:     0x55d208566ff2 - main
  28:     0x7f040f2a309b - __libc_start_main
  29:     0x55d2084c818a - _start
  30:                0x0 - <unknown>
```

**Comment by tobymurray** [comment]
Naively, I'll stream `Result` instead, so users can handle errors that bubble up. If the connection breaks in a way that doesn't resolve itself it'll get pretty loud.

At the same time I realized that my stream implementation will break for subs more active than ~25 posts/30 seconds. If it's critical that your bot see _every_ post, this library is not ready to support that case.

**Comment by tobymurray** [comment]
I've just pushed 0.1.20 that exposes this error for users to handle rather than panicking.
